### ISSUE TITLE
Maven support

### ISSUE THREAD

**Issue by dalb8** [veken0m/bitcoinium#8]
We at F-Droid project would like to distribute the app. Since there are many jars and the pom.xml is more or less written in the readme and pom.xml of the xchange repo it would be good to have a pom.xml here. If the jars in this repo were to change often it would be tedious for us to verify them (in the case that they are sourced from upstream) or to manually build them one by one from source.

**Comment by veken0m** [comment]
Closing this issue since Bitcoinium now uses Gradle for dependency management.
